# Generated by Django 3.1.5 on 2021-11-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Variable Name')),
                ('content', models.TextField(verbose_name='Variable Content')),
            ],
            options={
                'verbose_name_plural': 'Vars',
                'db_table': 'Config',
                'ordering': ['name'],
            },
        ),
    ]
