# Generated by Django 3.1.5 on 2021-11-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropotApp', '0002_auto_20211110_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Variable Content'),
        ),
    ]
