# Generated by Django 3.1.5 on 2021-11-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ropotApp', '0003_auto_20211111_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50, unique=True, verbose_name='إسم المنطقة')),
                ('selected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'المنطقة',
                'verbose_name_plural': 'المناطق',
                'db_table': 'Area',
                'ordering': ['-area_name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50, verbose_name='إسم الفرع')),
                ('selected', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ropotApp.area', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'الفرع',
                'verbose_name_plural': 'الفرع',
                'db_table': 'Branch',
                'ordering': ['-branch_name'],
            },
        ),
    ]
