# Generated by Django 3.1.5 on 2021-11-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ropotApp', '0004_area_branch_ror'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_record', models.DateField(auto_now=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'تسجيل السحب',
                'verbose_name_plural': 'تسجيلات السحب',
                'db_table': 'ROR',
                'ordering': ['-date_record'],
            },
        ),

    ]
