# Generated by Django 3.1.5 on 2022-01-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropotApp', '0005_ror'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappingLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='الإسم')),
                ('content', models.TextField(blank=True, null=True, verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(default=0, verbose_name='نوع السجل')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'سجلات',
                'db_table': 'ScrappingLogs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
